// Переопределения старых карточек Ford/Mazda
window.allGearboxData = window.allGearboxData || {};

Object.assign(window.allGearboxData, {
  "AKPP_6F35_Gen_I_II": {
    "gearbox": "6F35",
    "manufacturer": "Ford",
    "description": "6-ступенчатая АКПП Ford семейства 6F Mid-Range. В обычном сервисе обслуживается только жидкость: фильтр внутренний и в штатное ТО не входит.",
    "weak_points": "Основные риски 6F35: перегрев, загрязнение гидроблока, износ гидротрансформатора и ошибки по уровню ATF при обслуживании вне температурного окна.",
    "url": "",
    "cars": [],
    "summary": "6F35 | слив 3,8–4,7 л | пробки 12/8 Н·м | Mercon LV | контроль уровня 85–93 °C",
    "fluid": "Mercon LV",
    "drain_volume": 4.2,
    "fluid_type": "ATF Mercon LV",
    "fluid_spec": "Ford Mercon LV",
    "fill_range_celsius": "85-93",
    "work_temp_celsius": "90",
    "dry_capacity": "≈ 8,9 л",
    "service_interval": "Частичная замена каждые 60 000 км или 4 года; тяжёлый цикл — 30 000 км или 2 года",
    "pan_torque_nm": 0,
    "drain_torque_nm": 12,
    "fill_torque_nm": 8,
    "tools": [
      "подъёмник или эстакада, авто строго горизонтально",
      "шестигранник 11 мм для сливной пробки",
      "шестигранник 10 мм для пробки уровня",
      "динамометрический ключ",
      "OBD-сканер для контроля TFT"
    ],
    "parts_list": [
      "ATF Mercon LV 5 л",
      "сливная пробка CV6Z-7A010-A при износе или повреждении",
      "верхняя заливная крышка JM5Z-7B442-D при трещине/утере"
    ],
    "oem_json": {
      "oem_fluid_1": "XT-10-QLVC",
      "oem_fluid_1_price": 0,
      "oem_fluid_2": "XT-10-DLV",
      "oem_fluid_2_price": 0,
      "oem_filter_internal": "",
      "oem_filter_internal_price": 0,
      "oem_filter_internal_info": "Фильтр внутренний и при обычном ТО не меняется. 6F35 обслуживается через сливную и боковую контрольную пробки, поэтому OEM фильтра в сервисной карточке намеренно не указывается.",
      "oem_filter_external": "",
      "oem_filter_external_price": 0,
      "oem_filter_external_info": "Отдельного сервисного внешнего фильтра нет.",
      "oem_gasket_1": "",
      "oem_gasket_1_price": 0,
      "oem_gasket_1_info": "Съёмного нижнего поддона в обычной процедуре нет, отдельная прокладка поддона не требуется.",
      "oem_gasket_2": "",
      "oem_gasket_2_price": 0,
      "oem_gasket_2_info": "",
      "oem_o_ring_1": "",
      "oem_o_ring_1_price": 0,
      "oem_o_ring_1_info": "",
      "oem_o_ring_2": "",
      "oem_o_ring_2_price": 0,
      "oem_o_ring_2_info": "",
      "oem_drain_plug": "CV6Z-7A010-A",
      "oem_drain_plug_price": 0,
      "oem_drain_plug_info": "Сливная пробка 11 мм с интегрированным уплотнением.",
      "oem_drain_plug_washer": "",
      "oem_drain_plug_washer_price": 0,
      "oem_drain_plug_washer_info": "Отдельная шайба обычно не требуется, уплотнение встроено в пробку.",
      "oem_bolt_1": "JM5Z-7B442-D",
      "oem_bolt_1_price": 0,
      "oem_bolt_1_info": "Пластиковая верхняя крышка заливной трубки/вентиляции, затягивается вручную.",
      "oem_bolt_2": "",
      "oem_bolt_2_price": 0,
      "oem_bolt_2_info": "OEM боковой контрольной пробки без VIN открытыми каталогами надёжно не подтверждён."
    },
    "procedure": "Прогреть коробку, установить автомобиль строго горизонтально, ослабить боковую контрольную пробку, слить 3,8–4,7 л ATF через CV6Z-7A010-A, затянуть сливную пробку 12 Н·м и залить свежую Mercon LV через верхнюю крышку JM5Z-7B442-D. После цикла селектором уровень выставляют только при TFT 85–93 °C по контрольной пробке; если ATF ниже отверстия, доливать по 0,25 л до выхода ATF на уровень отверстия, затем затянуть пробку 8 Н·м.",
    "mistakes": [
      "Проверка уровня вне окна 85–93 °C.",
      "Использование жидкости без допуска Mercon LV.",
      "Перетяжка пробок и повреждение резьбы."
    ],
    "nuances": "У 6F35 нет обслуживаемого нижнего поддона; обычное ТО выполняется через сливную и боковую контрольную пробки. Фильтр внутренний и для стандартного ТО не считается сервисным расходником, поэтому его OEM в карточке не указан. Уровень выставляют только при TFT 85–93 °C."
  },
  "AKPP_5R55S5R55N5R55W": {
    "gearbox": "5R55S, 5R55N, 5R55W",
    "manufacturer": "Ford",
    "description": "Семейство 5-ступенчатых заднеприводных и полноприводных автоматов Ford.",
    "weak_points": "Чувствительны к перегреву, загрязнению гидроблока и износу ГДТ; конструкция поддона и подбор фильтра зависят от версии.",
    "url": "",
    "cars": [],
    "summary": "5R55S/5R55N/5R55W | слив 4–5 л | обычно MERCON V | уровень чаще по щупу | расходники и процедура зависят от поддона и автомобиля",
    "fluid": "ATF класса MERCON V",
    "drain_volume": 4.5,
    "fluid_type": "ATF MERCON V",
    "fluid_spec": "Уточнять по VIN и мануалу конкретного автомобиля",
    "fill_range_celsius": "70-90",
    "work_temp_celsius": "80",
    "dry_capacity": "≈ 10–12 л",
    "service_interval": "Ориентир 50 000–60 000 км; тяжёлый режим — чаще",
    "pan_torque_nm": 0,
    "drain_torque_nm": 0,
    "fill_torque_nm": 0,
    "tools": [
      "подъёмник или яма",
      "набор головок под конкретный поддон",
      "динамометрический ключ",
      "воронка/шланг для заливки через щуп",
      "сканер или пирометр для контроля температуры"
    ],
    "parts_list": [
      "ATF нужной спецификации",
      "фильтр АКПП по VIN",
      "прокладка поддона или герметик",
      "одноразовая шайба сливной пробки"
    ],
    "oem_json": {
      "oem_fluid_1": "",
      "oem_fluid_1_price": 0,
      "oem_fluid_2": "",
      "oem_fluid_2_price": 0,
      "oem_filter_internal": "",
      "oem_filter_internal_price": 0,
      "oem_filter_internal_info": "Фильтр подбирается по VIN и типу поддона.",
      "oem_filter_external": "",
      "oem_filter_external_price": 0,
      "oem_filter_external_info": "Штатного обслуживаемого внешнего фильтра обычно нет.",
      "oem_gasket_1": "",
      "oem_gasket_1_price": 0,
      "oem_gasket_1_info": "Прокладка зависит от исполнения поддона.",
      "oem_gasket_2": "",
      "oem_gasket_2_price": 0,
      "oem_gasket_2_info": "",
      "oem_o_ring_1": "",
      "oem_o_ring_1_price": 0,
      "oem_o_ring_1_info": "Уплотнения пробок и шейки фильтра уточняются по VIN.",
      "oem_o_ring_2": "",
      "oem_o_ring_2_price": 0,
      "oem_o_ring_2_info": "",
      "oem_drain_plug": "",
      "oem_drain_plug_price": 0,
      "oem_drain_plug_info": "Исполнение сливной пробки зависит от поддона.",
      "oem_drain_plug_washer": "",
      "oem_drain_plug_washer_price": 0,
      "oem_drain_plug_washer_info": "Шайбу желательно менять при каждом сливе.",
      "oem_bolt_1": "",
      "oem_bolt_1_price": 0,
      "oem_bolt_1_info": "Болты поддона и момент затяжки зависят от версии.",
      "oem_bolt_2": "",
      "oem_bolt_2_price": 0,
      "oem_bolt_2_info": ""
    },
    "procedure": "Стандартная схема: прогрев, слив ATF, снятие и очистка поддона, замена фильтра и прокладки, сборка, заливка свежей жидкости и контроль уровня по щупу или сервисной процедуре.",
    "mistakes": [
      "Подбор фильтра без проверки VIN.",
      "Контроль уровня без прогрева ATF.",
      "Повторное использование одноразовых уплотнений."
    ],
    "nuances": "У разных исполнений 5R55 отличаются поддоны, пробки и фильтры. Перед заказом расходников нужна сверка по VIN."
  },
  "AKPP_A4LD_E4R44E4R55E5R44E5R55EC3": {
    "gearbox": "A4LD-E, 4R44E, 4R55E, 5R44E, 5R55E (C3)",
    "manufacturer": "Ford",
    "description": "Семейство автоматов на базе C3 для заднеприводных и полноприводных Ford.",
    "weak_points": "Перегрев, износ тормозной ленты, загрязнение гидроблока и ошибки по подбору жидкости.",
    "url": "",
    "cars": [],
    "summary": "A4LD-E / 4R44E / 4R55E / 5R44E / 5R55E | слив 4–5 л | MERCON/MERCON V по версии | контроль уровня по щупу",
    "fluid": "ATF MERCON / MERCON V",
    "drain_volume": 4.5,
    "fluid_type": "ATF",
    "fluid_spec": "Допуск уточнять по VIN и году выпуска",
    "fill_range_celsius": "70-90",
    "work_temp_celsius": "80",
    "dry_capacity": "≈ 10–12 л",
    "service_interval": "Ориентир 50 000–60 000 км",
    "pan_torque_nm": 0,
    "drain_torque_nm": 0,
    "fill_torque_nm": 0,
    "tools": ["подъёмник", "ключи для поддона", "динамометрический ключ", "воронка/шланг", "ёмкость для слива"],
    "parts_list": ["ATF по допуску", "фильтр АКПП", "прокладка поддона", "уплотнение сливной пробки"],
    "oem_json": { "oem_fluid_1": "", "oem_fluid_1_price": 0, "oem_fluid_2": "", "oem_fluid_2_price": 0, "oem_filter_internal": "", "oem_filter_internal_price": 0, "oem_filter_internal_info": "Подбор фильтра по VIN и исполнению поддона.", "oem_filter_external": "", "oem_filter_external_price": 0, "oem_filter_external_info": "", "oem_gasket_1": "", "oem_gasket_1_price": 0, "oem_gasket_1_info": "Прокладка зависит от исполнения.", "oem_gasket_2": "", "oem_gasket_2_price": 0, "oem_gasket_2_info": "", "oem_o_ring_1": "", "oem_o_ring_1_price": 0, "oem_o_ring_1_info": "", "oem_o_ring_2": "", "oem_o_ring_2_price": 0, "oem_o_ring_2_info": "", "oem_drain_plug": "", "oem_drain_plug_price": 0, "oem_drain_plug_info": "Зависит от поддона.", "oem_drain_plug_washer": "", "oem_drain_plug_washer_price": 0, "oem_drain_plug_washer_info": "", "oem_bolt_1": "", "oem_bolt_1_price": 0, "oem_bolt_1_info": "", "oem_bolt_2": "", "oem_bolt_2_price": 0, "oem_bolt_2_info": "" },
    "procedure": "Частичный слив с обслуживанием поддона, заменой фильтра и последующей проверкой уровня по щупу на прогретой коробке.",
    "mistakes": ["Неверный допуск ATF.", "Игнорирование температуры при проверке уровня.", "Перетяжка крепежа поддона."],
    "nuances": "Для семейства C3 детали и допуски нужно проверять по году и VIN."
  },
  "AKPP_AODAOD_E4R70W4R75W4R70E4R75E": {
    "gearbox": "AOD, AOD-E, 4R70W, 4R75W, 4R70E, 4R75E",
    "manufacturer": "Ford",
    "description": "Крупное семейство полноразмерных автоматов Ford для мощных заднеприводных платформ.",
    "weak_points": "Перегрев, износ гидротрансформатора, течи, загрязнение гидроблока.",
    "url": "",
    "cars": [],
    "summary": "AOD / 4R70W / 4R75W | слив 4–6 л | MERCON/MERCON V по версии | уровень по щупу",
    "fluid": "ATF MERCON / MERCON V",
    "drain_volume": 5,
    "fluid_type": "ATF",
    "fluid_spec": "Проверять по году выпуска и табличке коробки",
    "fill_range_celsius": "70-90",
    "work_temp_celsius": "80",
    "dry_capacity": "≈ 12–14 л",
    "service_interval": "Ориентир 50 000–60 000 км; при тяжёлой эксплуатации чаще",
    "pan_torque_nm": 0,
    "drain_torque_nm": 0,
    "fill_torque_nm": 0,
    "tools": ["подъёмник", "набор головок", "динамометрический ключ", "воронка для щупа", "ёмкость для слива 15 л"],
    "parts_list": ["ATF по допуску", "сервисный фильтр", "прокладка поддона", "уплотнения пробок"],
    "oem_json": { "oem_fluid_1": "", "oem_fluid_1_price": 0, "oem_fluid_2": "", "oem_fluid_2_price": 0, "oem_filter_internal": "", "oem_filter_internal_price": 0, "oem_filter_internal_info": "Подбирать по VIN и типу поддона.", "oem_filter_external": "", "oem_filter_external_price": 0, "oem_filter_external_info": "Для тяжёлой эксплуатации часто ставят внешний радиатор, но не штатный фильтр.", "oem_gasket_1": "", "oem_gasket_1_price": 0, "oem_gasket_1_info": "", "oem_gasket_2": "", "oem_gasket_2_price": 0, "oem_gasket_2_info": "", "oem_o_ring_1": "", "oem_o_ring_1_price": 0, "oem_o_ring_1_info": "", "oem_o_ring_2": "", "oem_o_ring_2_price": 0, "oem_o_ring_2_info": "", "oem_drain_plug": "", "oem_drain_plug_price": 0, "oem_drain_plug_info": "", "oem_drain_plug_washer": "", "oem_drain_plug_washer_price": 0, "oem_drain_plug_washer_info": "", "oem_bolt_1": "", "oem_bolt_1_price": 0, "oem_bolt_1_info": "", "oem_bolt_2": "", "oem_bolt_2_price": 0, "oem_bolt_2_info": "" },
    "procedure": "Слить ATF, снять и очистить поддон, заменить фильтр, собрать узел, залить новый объём ATF и проверить уровень по щупу на холостом ходу.",
    "mistakes": ["Смешивание разных допусков ATF.", "Отсутствие охлаждения при тяжёлой эксплуатации.", "Перетяжка поддона."],
    "nuances": "Для 4R70/4R75 и ранних AOD детали поддона и фильтра могут различаться."
  },
  "AKPP_AX4N4F50N": {
    "gearbox": "AX4N, 4F50N",
    "manufacturer": "Ford",
    "description": "Переднеприводные 4-ступенчатые автоматы Ford для Taurus, Windstar и смежных моделей.",
    "weak_points": "Перегрев, проблемы гидроблока и ГДТ, чувствительность к состоянию масла.",
    "url": "",
    "cars": [],
    "summary": "AX4N / 4F50N | слив 4–5 л | обычно MERCON V | контроль уровня по щупу",
    "fluid": "ATF MERCON V",
    "drain_volume": 4.5,
    "fluid_type": "ATF MERCON V",
    "fluid_spec": "Проверять по VIN и мануалу",
    "fill_range_celsius": "70-90",
    "work_temp_celsius": "80",
    "dry_capacity": "≈ 9–11 л",
    "service_interval": "Ориентир 50 000–60 000 км",
    "pan_torque_nm": 0,
    "drain_torque_nm": 0,
    "fill_torque_nm": 0,
    "tools": ["подъёмник", "ключи для поддона", "динамометрический ключ", "воронка для щупа"],
    "parts_list": ["ATF MERCON V", "фильтр АКПП", "прокладка поддона"],
    "oem_json": { "oem_fluid_1": "", "oem_fluid_1_price": 0, "oem_fluid_2": "", "oem_fluid_2_price": 0, "oem_filter_internal": "", "oem_filter_internal_price": 0, "oem_filter_internal_info": "Подбирать по VIN.", "oem_filter_external": "", "oem_filter_external_price": 0, "oem_filter_external_info": "", "oem_gasket_1": "", "oem_gasket_1_price": 0, "oem_gasket_1_info": "", "oem_gasket_2": "", "oem_gasket_2_price": 0, "oem_gasket_2_info": "", "oem_o_ring_1": "", "oem_o_ring_1_price": 0, "oem_o_ring_1_info": "", "oem_o_ring_2": "", "oem_o_ring_2_price": 0, "oem_o_ring_2_info": "", "oem_drain_plug": "", "oem_drain_plug_price": 0, "oem_drain_plug_info": "", "oem_drain_plug_washer": "", "oem_drain_plug_washer_price": 0, "oem_drain_plug_washer_info": "", "oem_bolt_1": "", "oem_bolt_1_price": 0, "oem_bolt_1_info": "", "oem_bolt_2": "", "oem_bolt_2_price": 0, "oem_bolt_2_info": "" },
    "procedure": "Стандартное обслуживание с частичным сливом, снятием поддона, заменой фильтра и выставлением уровня по щупу на горячую.",
    "mistakes": ["Перегрев коробки без чистки радиатора.", "Эксплуатация на старой ATF."],
    "nuances": "На поздних 4F50N и ранних AX4N могут отличаться отдельные расходники."
  },
  "AKPP_AXOD_AXOD_E_AX4S": {
    "gearbox": "AXOD/AXOD-E/AX4S",
    "manufacturer": "Ford",
    "description": "Ранние переднеприводные автоматы Ford семейства AXOD/AX4S.",
    "weak_points": "Высокая чувствительность к загрязнённому маслу и перегреву.",
    "url": "",
    "cars": [],
    "summary": "AXOD / AXOD-E / AX4S | слив 4–5 л | MERCON/MERCON V по версии | уровень по щупу",
    "fluid": "ATF MERCON / MERCON V",
    "drain_volume": 4.5,
    "fluid_type": "ATF",
    "fluid_spec": "Подбирать по году выпуска и мануалу",
    "fill_range_celsius": "70-90",
    "work_temp_celsius": "80",
    "dry_capacity": "≈ 9–10 л",
    "service_interval": "Желательно 40 000–50 000 км",
    "pan_torque_nm": 0,
    "drain_torque_nm": 0,
    "fill_torque_nm": 0,
    "tools": ["подъёмник", "ключи для поддона", "воронка/шланг", "ёмкость для слива"],
    "parts_list": ["ATF по допуску", "фильтр АКПП", "прокладка поддона"],
    "oem_json": { "oem_fluid_1": "", "oem_fluid_1_price": 0, "oem_fluid_2": "", "oem_fluid_2_price": 0, "oem_filter_internal": "", "oem_filter_internal_price": 0, "oem_filter_internal_info": "Зависит от версии AXOD/AX4S.", "oem_filter_external": "", "oem_filter_external_price": 0, "oem_filter_external_info": "", "oem_gasket_1": "", "oem_gasket_1_price": 0, "oem_gasket_1_info": "", "oem_gasket_2": "", "oem_gasket_2_price": 0, "oem_gasket_2_info": "", "oem_o_ring_1": "", "oem_o_ring_1_price": 0, "oem_o_ring_1_info": "", "oem_o_ring_2": "", "oem_o_ring_2_price": 0, "oem_o_ring_2_info": "", "oem_drain_plug": "", "oem_drain_plug_price": 0, "oem_drain_plug_info": "", "oem_drain_plug_washer": "", "oem_drain_plug_washer_price": 0, "oem_drain_plug_washer_info": "", "oem_bolt_1": "", "oem_bolt_1_price": 0, "oem_bolt_1_info": "", "oem_bolt_2": "", "oem_bolt_2_price": 0, "oem_bolt_2_info": "" },
    "procedure": "Обычный сервис со снятием поддона, чисткой магнитов, заменой фильтра и контролем уровня по щупу.",
    "mistakes": ["Редкая замена ATF.", "Езда на перегретой коробке."],
    "nuances": "Для старых коробок часто разумнее делать две последовательные частичные замены."
  },
  "AKPP_CD4ELA4A_EL4F44E": {
    "gearbox": "CD4E, LA4A-EL (4F44E)",
    "manufacturer": "Ford",
    "description": "4-ступенчатая переднеприводная АКПП Ford/Mazda для моторов 2.0–2.5 л.",
    "weak_points": "Тормозная лента, маслонасос, гидроблок и перегрев.",
    "url": "",
    "cars": [],
    "summary": "CD4E / LA4A-EL (4F44E) | слив 4–5 л | обычно MERCON V | контроль уровня по щупу или сервисной процедуре",
    "fluid": "ATF MERCON V",
    "drain_volume": 4.5,
    "fluid_type": "ATF MERCON V",
    "fluid_spec": "Уточнять по VIN и рынку",
    "fill_range_celsius": "70-90",
    "work_temp_celsius": "80",
    "dry_capacity": "≈ 8–9 л",
    "service_interval": "Ориентир 40 000–60 000 км",
    "pan_torque_nm": 0,
    "drain_torque_nm": 0,
    "fill_torque_nm": 0,
    "tools": ["подъёмник", "ключи для поддона", "динамометрический ключ", "воронка/насос"],
    "parts_list": ["ATF MERCON V", "фильтр АКПП", "прокладка поддона", "уплотнения пробок"],
    "oem_json": { "oem_fluid_1": "", "oem_fluid_1_price": 0, "oem_fluid_2": "", "oem_fluid_2_price": 0, "oem_filter_internal": "", "oem_filter_internal_price": 0, "oem_filter_internal_info": "Фильтр и прокладка подбираются по VIN.", "oem_filter_external": "", "oem_filter_external_price": 0, "oem_filter_external_info": "", "oem_gasket_1": "", "oem_gasket_1_price": 0, "oem_gasket_1_info": "", "oem_gasket_2": "", "oem_gasket_2_price": 0, "oem_gasket_2_info": "", "oem_o_ring_1": "", "oem_o_ring_1_price": 0, "oem_o_ring_1_info": "", "oem_o_ring_2": "", "oem_o_ring_2_price": 0, "oem_o_ring_2_info": "", "oem_drain_plug": "", "oem_drain_plug_price": 0, "oem_drain_plug_info": "", "oem_drain_plug_washer": "", "oem_drain_plug_washer_price": 0, "oem_drain_plug_washer_info": "", "oem_bolt_1": "", "oem_bolt_1_price": 0, "oem_bolt_1_info": "", "oem_bolt_2": "", "oem_bolt_2_price": 0, "oem_bolt_2_info": "" },
    "procedure": "Частичный слив, снятие поддона, осмотр ленты и насоса, замена фильтра, сборка и контроль уровня.",
    "mistakes": ["Игнорирование износа ленты.", "Перегрев коробки.", "Подбор расходников без VIN."],
    "nuances": "На части версий применяются кросс-номера Ford/Mazda, поэтому расходники нужно сверять по каталогу."
  },
  "AKPP_E40D4R100C6": {
    "gearbox": "E4OD, 4R100, C6",
    "manufacturer": "Ford",
    "description": "Тяжёлые автоматы Ford для пикапов, внедорожников и коммерческого транспорта.",
    "weak_points": "Перегрев под нагрузкой, загрязнение гидроблока, износ входного вала и насоса.",
    "url": "",
    "cars": [],
    "summary": "E4OD / 4R100 / C6 | слив 5–7 л | MERCON/MERCON V по версии | уровень по щупу | критично состояние охлаждения",
    "fluid": "ATF MERCON / MERCON V",
    "drain_volume": 6,
    "fluid_type": "ATF",
    "fluid_spec": "Уточнять по году и автомобилю",
    "fill_range_celsius": "70-90",
    "work_temp_celsius": "85",
    "dry_capacity": "≈ 14–16 л",
    "service_interval": "Ориентир 40 000–50 000 км; при буксировке и тяжёлой эксплуатации чаще",
    "pan_torque_nm": 0,
    "drain_torque_nm": 0,
    "fill_torque_nm": 0,
    "tools": ["подъёмник", "ёмкость для слива 20 л", "ключи для поддона", "воронка для щупа"],
    "parts_list": ["ATF по допуску", "фильтр АКПП", "прокладка поддона", "уплотнения пробок"],
    "oem_json": { "oem_fluid_1": "", "oem_fluid_1_price": 0, "oem_fluid_2": "", "oem_fluid_2_price": 0, "oem_filter_internal": "", "oem_filter_internal_price": 0, "oem_filter_internal_info": "Подбирать по VIN и версии коробки.", "oem_filter_external": "", "oem_filter_external_price": 0, "oem_filter_external_info": "Штатного внешнего фильтра обычно нет, но охлаждение критично.", "oem_gasket_1": "", "oem_gasket_1_price": 0, "oem_gasket_1_info": "", "oem_gasket_2": "", "oem_gasket_2_price": 0, "oem_gasket_2_info": "", "oem_o_ring_1": "", "oem_o_ring_1_price": 0, "oem_o_ring_1_info": "", "oem_o_ring_2": "", "oem_o_ring_2_price": 0, "oem_o_ring_2_info": "", "oem_drain_plug": "", "oem_drain_plug_price": 0, "oem_drain_plug_info": "", "oem_drain_plug_washer": "", "oem_drain_plug_washer_price": 0, "oem_drain_plug_washer_info": "", "oem_bolt_1": "", "oem_bolt_1_price": 0, "oem_bolt_1_info": "", "oem_bolt_2": "", "oem_bolt_2_price": 0, "oem_bolt_2_info": "" },
    "procedure": "Слить жидкость, обслужить поддон и фильтр, залить свежую ATF, прогреть коробку и перепроверить уровень после тест-драйва под нагрузкой.",
    "mistakes": ["Буксировка без контроля температуры ATF.", "Редкая замена масла.", "Грязный радиатор охлаждения."],
    "nuances": "Для E4OD/4R100 ресурс сильно зависит от температуры и состояния системы охлаждения."
  },
  "AKPP_FW6A_ELGW6A_EL": {
    "gearbox": "FW6A-EL, GW6A-EL",
    "manufacturer": "Mazda",
    "description": "6-ступенчатая автоматическая коробка Mazda/Aisin для переднеприводных Mazda Skyactiv.",
    "weak_points": "Износ ГДТ, загрязнение гидроблока и чувствительность к нарушению уровня.",
    "url": "",
    "cars": [],
    "summary": "FW6A-EL / GW6A-EL | слив ≈ 3,3 л | ATF-FZ | контроль уровня 45–55 °C | ранние и поздние версии отличаются по способу проверки",
    "fluid": "Mazda ATF-FZ",
    "drain_volume": 3.3,
    "fluid_type": "ATF-FZ",
    "fluid_spec": "Mazda ATF-FZ",
    "fill_range_celsius": "45-55",
    "work_temp_celsius": "50",
    "dry_capacity": "7,9 л",
    "service_interval": "60 000 км или 4 года; тяжёлый режим — 30 000 км или 2 года",
    "pan_torque_nm": 0,
    "drain_torque_nm": 35,
    "fill_torque_nm": 9,
    "tools": ["подъёмник", "шестигранник 8 мм", "болт щупа 10 мм", "динамометрический ключ", "OBD-сканер для TFT"],
    "parts_list": ["Mazda ATF-FZ 5 л", "сливная пробка FS50-21-249", "кольцо 9956-41-400", "щуп/болт уровня по версии"],
    "oem_json": {
      "oem_fluid_1": "0000-FZ-113E-01",
      "oem_fluid_1_price": 0,
      "oem_fluid_2": "AJ00-FZ-113E",
      "oem_fluid_2_price": 0,
      "oem_filter_internal": "",
      "oem_filter_internal_price": 0,
      "oem_filter_internal_info": "Фильтр встроен и меняется при разборке гидроблока.",
      "oem_filter_external": "",
      "oem_filter_external_price": 0,
      "oem_filter_external_info": "Отдельного внешнего сервисного фильтра нет.",
      "oem_gasket_1": "",
      "oem_gasket_1_price": 0,
      "oem_gasket_1_info": "",
      "oem_gasket_2": "",
      "oem_gasket_2_price": 0,
      "oem_gasket_2_info": "",
      "oem_o_ring_1": "9956-41-400",
      "oem_o_ring_1_price": 0,
      "oem_o_ring_1_info": "Медная шайба сливной пробки.",
      "oem_o_ring_2": "9956-41-800",
      "oem_o_ring_2_price": 0,
      "oem_o_ring_2_info": "",
      "oem_drain_plug": "FS50-21-249",
      "oem_drain_plug_price": 0,
      "oem_drain_plug_info": "Сливная пробка 8 мм.",
      "oem_drain_plug_washer": "9956-41-400",
      "oem_drain_plug_washer_price": 0,
      "oem_drain_plug_washer_info": "Шайбу желательно менять при каждом сливе.",
      "oem_bolt_1": "",
      "oem_bolt_1_price": 0,
      "oem_bolt_1_info": "Болт щупа уровня зависит от версии.",
      "oem_bolt_2": "",
      "oem_bolt_2_price": 0,
      "oem_bolt_2_info": ""
    },
    "procedure": "Прогреть трансмиссию, слить ATF через сливную пробку, залить объём слитого плюс небольшой запас, затем выставить уровень по щупу или сервисной процедуре при TFT 45–55 °C.",
    "mistakes": ["Проверка уровня вне температурного окна.", "Использование ATF не класса FZ.", "Перетяжка сливной пробки."],
    "nuances": "На ранних версиях используется щуп, на поздних возможна другая методика контроля уровня."
  },
  "AKPP_FW6A_EL": {
    "gearbox": "FW6A-EL, GW6A-EL",
    "manufacturer": "Mazda",
    "description": "Актуализированная карточка Mazda для FW6A-EL / GW6A-EL.",
    "weak_points": "Износ ГДТ и загрязнение гидроблока при редкой замене ATF.",
    "url": "",
    "cars": [],
    "summary": "FW6A-EL / GW6A-EL | слив ≈ 3,3 л | ATF-FZ | контроль уровня 45–55 °C",
    "fluid": "Mazda ATF-FZ",
    "drain_volume": 3.3,
    "fluid_type": "ATF-FZ",
    "fluid_spec": "Mazda ATF-FZ",
    "fill_range_celsius": "45-55",
    "work_temp_celsius": "50",
    "dry_capacity": "7,9 л",
    "service_interval": "60 000 км или 4 года",
    "pan_torque_nm": 0,
    "drain_torque_nm": 35,
    "fill_torque_nm": 9,
    "tools": ["подъёмник", "шестигранник 8 мм", "сканер TFT"],
    "parts_list": ["ATF-FZ", "сливная пробка", "шайба пробки"],
    "oem_json": { "oem_fluid_1": "0000-FZ-113E-01", "oem_fluid_1_price": 0, "oem_fluid_2": "AJ00-FZ-113E", "oem_fluid_2_price": 0, "oem_filter_internal": "", "oem_filter_internal_price": 0, "oem_filter_internal_info": "Фильтр встроен.", "oem_filter_external": "", "oem_filter_external_price": 0, "oem_filter_external_info": "", "oem_gasket_1": "", "oem_gasket_1_price": 0, "oem_gasket_1_info": "", "oem_gasket_2": "", "oem_gasket_2_price": 0, "oem_gasket_2_info": "", "oem_o_ring_1": "9956-41-400", "oem_o_ring_1_price": 0, "oem_o_ring_1_info": "", "oem_o_ring_2": "9956-41-800", "oem_o_ring_2_price": 0, "oem_o_ring_2_info": "", "oem_drain_plug": "FS50-21-249", "oem_drain_plug_price": 0, "oem_drain_plug_info": "", "oem_drain_plug_washer": "9956-41-400", "oem_drain_plug_washer_price": 0, "oem_drain_plug_washer_info": "", "oem_bolt_1": "", "oem_bolt_1_price": 0, "oem_bolt_1_info": "", "oem_bolt_2": "", "oem_bolt_2_price": 0, "oem_bolt_2_info": "" },
    "procedure": "Слить ATF, залить свежую жидкость, прогреть коробку и выставить уровень при 45–55 °C.",
    "mistakes": ["Неверная температура проверки.", "Использование неподходящей жидкости."],
    "nuances": "Разные ревизии используют разные способы контроля уровня."
  },
  "AKPP_6F24": {
    "gearbox": "6F24",
    "manufacturer": "SsangYong",
    "description": "6-ступенчатая АКПП, применявшаяся на ряде моделей SsangYong и смежных платформ.",
    "weak_points": "Износ ГДТ, загрязнение гидроблока, возможные отличия по допуску ATF в зависимости от автомобиля.",
    "url": "",
    "cars": [],
    "summary": "6F24 | слив 4–5 л | ATF по допуску конкретного автомобиля | уровень по щупу или сервисной пробке, зависит от исполнения",
    "fluid": "ATF по допуску производителя автомобиля",
    "drain_volume": 4.5,
    "fluid_type": "ATF",
    "fluid_spec": "Уточнять по конкретному автомобилю и рынку",
    "fill_range_celsius": "уточнять по мануалу",
    "work_temp_celsius": "80",
    "dry_capacity": "≈ 7–9 л",
    "service_interval": "Ориентир 50 000–60 000 км",
    "pan_torque_nm": 0,
    "drain_torque_nm": 0,
    "fill_torque_nm": 0,
    "tools": ["подъёмник", "ключи под поддон", "насос/шприц для ATF", "OBD-сканер"],
    "parts_list": ["ATF по допуску", "фильтр АКПП по версии", "прокладка поддона", "уплотнения пробок"],
    "oem_json": { "oem_fluid_1": "", "oem_fluid_1_price": 0, "oem_fluid_2": "", "oem_fluid_2_price": 0, "oem_filter_internal": "", "oem_filter_internal_price": 0, "oem_filter_internal_info": "Фильтр и его сервисность зависят от конкретной версии 6F24.", "oem_filter_external": "", "oem_filter_external_price": 0, "oem_filter_external_info": "", "oem_gasket_1": "", "oem_gasket_1_price": 0, "oem_gasket_1_info": "Поддон и прокладка зависят от исполнения.", "oem_gasket_2": "", "oem_gasket_2_price": 0, "oem_gasket_2_info": "", "oem_o_ring_1": "", "oem_o_ring_1_price": 0, "oem_o_ring_1_info": "", "oem_o_ring_2": "", "oem_o_ring_2_price": 0, "oem_o_ring_2_info": "", "oem_drain_plug": "", "oem_drain_plug_price": 0, "oem_drain_plug_info": "", "oem_drain_plug_washer": "", "oem_drain_plug_washer_price": 0, "oem_drain_plug_washer_info": "", "oem_bolt_1": "", "oem_bolt_1_price": 0, "oem_bolt_1_info": "", "oem_bolt_2": "", "oem_bolt_2_price": 0, "oem_bolt_2_info": "" },
    "procedure": "Сервис выполняется по схеме конкретного автомобиля: слив, при необходимости снятие поддона и фильтра, заливка свежей жидкости и контроль уровня по штатной процедуре.",
    "mistakes": ["Назначение универсального допуска ATF без проверки мануала.", "Подбор расходников без VIN."],
    "nuances": "Коробка встречается на разных автомобилях, поэтому расходники и процедура могут заметно отличаться."
  },

  // Пустые заглушки для остальных АКПП Ford из списка,
  // чтобы они появились в интерфейсе (без заполненных данных).
  "FORD_AXOD": { "gearbox": "AXOD", "manufacturer": "Ford" },
  "FORD_AX4N": { "gearbox": "AX4N", "manufacturer": "Ford" },
  "FORD_AX4S": { "gearbox": "AX4S", "manufacturer": "Ford" },
  "FORD_CD4E": { "gearbox": "CD4E", "manufacturer": "Ford" },
  "FORD_4EAT_G": { "gearbox": "4EAT-G", "manufacturer": "Ford" },
  "FORD_4EAT_F": { "gearbox": "4EAT-F", "manufacturer": "Ford" },
  "FORD_4F27": { "gearbox": "4F27", "manufacturer": "Ford" },
  "FORD_4F44": { "gearbox": "4F44", "manufacturer": "Ford" },
  "FORD_4F50": { "gearbox": "4F50", "manufacturer": "Ford" },
  "FORD_A4LD": { "gearbox": "A4LD", "manufacturer": "Ford" },
  "FORD_AODE": { "gearbox": "AODE", "manufacturer": "Ford" },
  "FORD_E4OD": { "gearbox": "E4OD", "manufacturer": "Ford" },
  "FORD_4R44": { "gearbox": "4R44", "manufacturer": "Ford" },
  "FORD_4R55": { "gearbox": "4R55", "manufacturer": "Ford" },
  "FORD_4R70": { "gearbox": "4R70", "manufacturer": "Ford" },
  "FORD_4R75": { "gearbox": "4R75", "manufacturer": "Ford" },
  "FORD_4R100": { "gearbox": "4R100", "manufacturer": "Ford" },
  "FORD_5F27": { "gearbox": "5F27", "manufacturer": "Ford" },
  "FORD_5F31": { "gearbox": "5F31", "manufacturer": "Ford" },
  "FORD_5R44": { "gearbox": "5R44", "manufacturer": "Ford" },
  "FORD_5R55": { "gearbox": "5R55", "manufacturer": "Ford" },
  "FORD_5R110": { "gearbox": "5R110", "manufacturer": "Ford" },
  "FORD_6F15": { "gearbox": "6F15", "manufacturer": "Ford" },
  "FORD_6F50": { "gearbox": "6F50", "manufacturer": "Ford" },
  "FORD_6F55": { "gearbox": "6F55", "manufacturer": "Ford" },
  "FORD_AWF21": { "gearbox": "AWF21", "manufacturer": "Ford" },
  "FORD_6R60": { "gearbox": "6R60", "manufacturer": "Ford" },
  "FORD_6R75": { "gearbox": "6R75", "manufacturer": "Ford" },
  "FORD_6R80": { "gearbox": "6R80", "manufacturer": "Ford" },
  "FORD_6R100": { "gearbox": "6R100", "manufacturer": "Ford" },
  "FORD_6R140": { "gearbox": "6R140", "manufacturer": "Ford" },
  "FORD_7F40": { "gearbox": "7F40", "manufacturer": "Ford" },
  "FORD_8F24": { "gearbox": "8F24", "manufacturer": "Ford" },
  "FORD_8F35": { "gearbox": "8F35", "manufacturer": "Ford" },
  "FORD_8F40": { "gearbox": "8F40", "manufacturer": "Ford" },
  "FORD_8F57": { "gearbox": "8F57", "manufacturer": "Ford" },
  "FORD_10R60": {
    "gearbox": "10R60",
    "manufacturer": "Ford",
    "description": "10-ступенчатая АКПП Ford для продольных RWD/4WD-платформ. В штатной сервисной процедуре слив выполняется через снятие поддона, уровень проверяется по щупу-индикатору.",
    "weak_points": "Для 10R60 критичны чистота ATF, точный уровень и отсутствие перегрева. Коробка чувствительна к переливу, грязному маслу и ошибкам при прогреве перед финальной проверкой уровня.",
    "url": "",
    "cars": [],
    "summary": "10R60 | первичная заливка 4,8 л после снятия поддона | заливная пробка 47 Н·м | Mercon ULV | проверка уровня по щупу при 96–101 °C",
    "fluid": "Motorcraft Mercon ULV",
    "drain_volume": 4.8,
    "fluid_type": "ATF Mercon ULV",
    "fluid_spec": "Ford WSS-M2C949-A / Mercon ULV",
    "fill_range_celsius": "96-101",
    "work_temp_celsius": "98",
    "dry_capacity": "12,2 л",
    "service_interval": "50 000–60 000 км или 4 года; при тяжёлой эксплуатации лучше 40 000 км",
    "pan_torque_nm": 0,
    "drain_torque_nm": 0,
    "fill_torque_nm": 47,
    "tools": [
      "подъёмник или эстакада, автомобиль строго горизонтально",
      "набор головок для защиты и поддона",
      "насос или фирменная трубка для заливки через сервисное отверстие",
      "шприц/отсос для удаления лишней ATF",
      "OBD-сканер для контроля температуры TFT",
      "динамометрический ключ до 50 Н·м"
    ],
    "parts_list": [
      "Mercon ULV 5–6 л",
      "фильтр АКПП MB3Z-7G186-A / FT-231",
      "прокладка поддона HL3Z-7A191-B",
      "очиститель поддона и магнитов"
    ],
    "oem_json": {
      "oem_fluid_1": "XT-12-QULV",
      "oem_fluid_1_price": 0,
      "oem_fluid_2": "",
      "oem_fluid_2_price": 0,
      "oem_filter_internal": "MB3Z-7G186-A",
      "oem_filter_internal_price": 0,
      "oem_filter_internal_info": "Сервисный фильтр нижнего поддона. Motorcraft номер FT-231; в части каталогов указан как замена LP5Z-7A098-A. В некоторых агрегаторах встречается HL3Z-7A098-A, поэтому перед заказом лучше сверять по VIN.",
      "oem_filter_external": "",
      "oem_filter_external_price": 0,
      "oem_filter_external_info": "Отдельного внешнего сервисного фильтра нет.",
      "oem_gasket_1": "HL3Z-7A191-B",
      "oem_gasket_1_price": 0,
      "oem_gasket_1_info": "Прокладка нижнего поддона; заменяет более ранний номер HL3Z-7A191-A.",
      "oem_gasket_2": "",
      "oem_gasket_2_price": 0,
      "oem_gasket_2_info": "",
      "oem_o_ring_1": "",
      "oem_o_ring_1_price": 0,
      "oem_o_ring_1_info": "",
      "oem_o_ring_2": "",
      "oem_o_ring_2_price": 0,
      "oem_o_ring_2_info": "",
      "oem_drain_plug": "",
      "oem_drain_plug_price": 0,
      "oem_drain_plug_info": "В штатной конфигурации слив выполняется через снятие поддона, отдельная сливная пробка обычно отсутствует.",
      "oem_drain_plug_washer": "",
      "oem_drain_plug_washer_price": 0,
      "oem_drain_plug_washer_info": "",
      "oem_bolt_1": "",
      "oem_bolt_1_price": 0,
      "oem_bolt_1_info": "Заливная пробка затягивается моментом 47 Н·м; точный OEM открытыми каталогами без VIN надёжно не подтверждён.",
      "oem_bolt_2": "",
      "oem_bolt_2_price": 0,
      "oem_bolt_2_info": ""
    },
    "procedure": "1. Установите автомобиль строго горизонтально и снимите защиту.\n2. Для штатной процедуры снимите нижний поддон АКПП и слейте масло; отдельно снимать фильтр только ради слива не требуется, но при сервисе поддона фильтр сервисный и обычно меняется.\n3. Очистите поддон и магниты, установите новый фильтр и прокладку, затем соберите узел.\n4. Снимите заливную пробку и извлеките щуп-индикатор.\n5. Через сервисное отверстие залейте 4,8 л свежего Mercon ULV как первичную заправку.\n6. Запустите двигатель и переведите селектор через все режимы, удерживая примерно по 5 секунд в каждом положении, затем верните в «P».\n7. Прогрейте коробку в движении до TFT 96–101 °C.\n8. На работающем двигателе в положении «P» проверьте уровень по щупу; горячий уровень должен находиться в зоне между отметками 3 и 4.5.\n9. При недоливе добавляйте Mercon ULV малыми порциями, при переливе удаляйте излишек отсосом.\n10. Установите щуп и затяните заливную пробку моментом 47 Н·м.\n11. После короткой поездки повторно проверьте коробку на подтёки.",
    "mistakes": [
      "Использование любого ATF кроме Mercon ULV.",
      "Финальная проверка уровня на холодной коробке.",
      "Перелив или недолив после сервиса.",
      "Обслуживание без контроля температуры TFT.",
      "Попытка грубо промыть очень грязную коробку за один цикл."
    ],
    "nuances": "10R60 обслуживается не по переливной трубке, а по щупу-индикатору. Штатная процедура подразумевает снятие нижнего поддона для слива, поэтому фильтр здесь сервисный и доступен при обычном обслуживании. Коробка очень чувствительна к переполнению, поэтому финальный уровень выставляют только на полностью прогретой ATF 96–101 °C."
  },
  "FORD_10R80": { "gearbox": "10R80", "manufacturer": "Ford" },
  "FORD_10R140": { "gearbox": "10R140", "manufacturer": "Ford" },
  "FORD_DPS6": { "gearbox": "DPS6", "manufacturer": "Ford" },
  "FORD_MPS6": { "gearbox": "MPS6", "manufacturer": "Ford" },
  "FORD_MPS6i": { "gearbox": "MPS6i", "manufacturer": "Ford" },
  "FORD_CFT23": { "gearbox": "CFT23", "manufacturer": "Ford" },
  "FORD_CFT30": { "gearbox": "CFT30", "manufacturer": "Ford" }
});
