// Переопределения старых карточек Ford/Mazda
window.allGearboxData = window.allGearboxData || {};

Object.assign(window.allGearboxData, {
  "AKPP_6F35_Gen_I_II": {
    "gearbox": "6F35",
    "manufacturer": "Ford",
    "description": "6-ступенчатая автоматическая коробка Ford семейства 6F35. Основные параметры обслуживания зависят от поколения и исполнения уровня.",
    "weak_points": "К чувствительным зонам относят перегрев, загрязнение гидроблока, износ ГДТ и ошибки по уровню ATF при обслуживании вне температурного окна.",
    "url": "",
    "cars": [],
    "summary": "6F35 | слив 3,8–4,7 л | Mercon LV | контроль уровня 85–93 °C | для ранних и поздних версий возможны отличия по способу проверки",
    "fluid": "Mercon LV",
    "drain_volume": 4.2,
    "fluid_type": "ATF Mercon LV",
    "fluid_spec": "Ford Mercon LV",
    "fill_range_celsius": "85-93",
    "work_temp_celsius": "90",
    "dry_capacity": "≈ 8,9 л",
    "service_interval": "Частичная замена каждые 60 000 км или 4 года; тяжёлый цикл — 30 000 км или 2 года",
    "pan_torque_nm": 0,
    "drain_torque_nm": 12,
    "fill_torque_nm": 8,
    "tools": [
      "подъёмник или эстакада, авто строго горизонтально",
      "шестигранник 11 мм для сливной пробки",
      "шестигранник 10 мм для пробки уровня",
      "динамометрический ключ",
      "OBD-сканер для контроля TFT"
    ],
    "parts_list": [
      "ATF Mercon LV 5 л",
      "сливная пробка CV6Z-7A010-A",
      "пробка уровня M10",
      "верхняя заливная крышка JM5Z-7B442-D"
    ],
    "oem_json": {
      "oem_fluid_1": "XT-10-QLV",
      "oem_fluid_1_price": 0,
      "oem_fluid_2": "XT-10-DLV",
      "oem_fluid_2_price": 0,
      "oem_filter_internal": "",
      "oem_filter_internal_price": 0,
      "oem_filter_internal_info": "Фильтр встроен и при обычном ТО не меняется.",
      "oem_filter_external": "",
      "oem_filter_external_price": 0,
      "oem_filter_external_info": "Отдельного сервисного внешнего фильтра нет.",
      "oem_gasket_1": "",
      "oem_gasket_1_price": 0,
      "oem_gasket_1_info": "Отдельная прокладка поддона в обычной процедуре не используется.",
      "oem_gasket_2": "",
      "oem_gasket_2_price": 0,
      "oem_gasket_2_info": "",
      "oem_o_ring_1": "",
      "oem_o_ring_1_price": 0,
      "oem_o_ring_1_info": "",
      "oem_o_ring_2": "",
      "oem_o_ring_2_price": 0,
      "oem_o_ring_2_info": "",
      "oem_drain_plug": "CV6Z-7A010-A",
      "oem_drain_plug_price": 0,
      "oem_drain_plug_info": "Сливная пробка 11 мм, исполнение зависит от версии.",
      "oem_drain_plug_washer": "",
      "oem_drain_plug_washer_price": 0,
      "oem_drain_plug_washer_info": "Уточнять по исполнению пробки.",
      "oem_bolt_1": "JM5Z-7B442-D",
      "oem_bolt_1_price": 0,
      "oem_bolt_1_info": "Пластиковая верхняя крышка заливного отверстия.",
      "oem_bolt_2": "",
      "oem_bolt_2_price": 0,
      "oem_bolt_2_info": ""
    },
    "procedure": "Прогреть АКПП, выставить автомобиль строго горизонтально, слить ATF, предварительно убедившись в доступности контрольной пробки. Залить свежую Mercon LV, прогнать селектор по всем положениям и выставить уровень только при TFT 85–93 °C.",
    "mistakes": [
      "Проверка уровня до прогрева термоклапана.",
      "Использование жидкости без допуска Mercon LV.",
      "Перетяжка пробок и повреждение резьбы."
    ],
    "nuances": "Ранние и поздние версии 6F35 отличаются по способу контроля уровня. Перед сервисом желательно сверять процедуру по конкретному автомобилю."
  },
  "AKPP_5R55S5R55N5R55W": {
    "gearbox": "5R55S, 5R55N, 5R55W",
    "manufacturer": "Ford",
    "description": "Семейство 5-ступенчатых заднеприводных и полноприводных автоматов Ford.",
    "weak_points": "Чувствительны к перегреву, загрязнению гидроблока и износу ГДТ; конструкция поддона и подбор фильтра зависят от версии.",
    "url": "",
    "cars": [],
    "summary": "5R55S/5R55N/5R55W | слив 4–5 л | обычно MERCON V | уровень чаще по щупу | расходники и процедура зависят от поддона и автомобиля",
    "fluid": "ATF класса MERCON V",
    "drain_volume": 4.5,
    "fluid_type": "ATF MERCON V",
    "fluid_spec": "Уточнять по VIN и мануалу конкретного автомобиля",
    "fill_range_celsius": "70-90",
    "work_temp_celsius": "80",
    "dry_capacity": "≈ 10–12 л",
    "service_interval": "Ориентир 50 000–60 000 км; тяжёлый режим — чаще",
    "pan_torque_nm": 0,
    "drain_torque_nm": 0,
    "fill_torque_nm": 0,
    "tools": [
      "подъёмник или яма",
      "набор головок под конкретный поддон",
      "динамометрический ключ",
      "воронка/шланг для заливки через щуп",
      "сканер или пирометр для контроля температуры"
    ],
    "parts_list": [
      "ATF нужной спецификации",
      "фильтр АКПП по VIN",
      "прокладка поддона или герметик",
      "одноразовая шайба сливной пробки"
    ],
    "oem_json": {
      "oem_fluid_1": "",
      "oem_fluid_1_price": 0,
      "oem_fluid_2": "",
      "oem_fluid_2_price": 0,
      "oem_filter_internal": "",
      "oem_filter_internal_price": 0,
      "oem_filter_internal_info": "Фильтр подбирается по VIN и типу поддона.",
      "oem_filter_external": "",
      "oem_filter_external_price": 0,
      "oem_filter_external_info": "Штатного обслуживаемого внешнего фильтра обычно нет.",
      "oem_gasket_1": "",
      "oem_gasket_1_price": 0,
      "oem_gasket_1_info": "Прокладка зависит от исполнения поддона.",
      "oem_gasket_2": "",
      "oem_gasket_2_price": 0,
      "oem_gasket_2_info": "",
      "oem_o_ring_1": "",
      "oem_o_ring_1_price": 0,
      "oem_o_ring_1_info": "Уплотнения пробок и шейки фильтра уточняются по VIN.",
      "oem_o_ring_2": "",
      "oem_o_ring_2_price": 0,
      "oem_o_ring_2_info": "",
      "oem_drain_plug": "",
      "oem_drain_plug_price": 0,
      "oem_drain_plug_info": "Исполнение сливной пробки зависит от поддона.",
      "oem_drain_plug_washer": "",
      "oem_drain_plug_washer_price": 0,
      "oem_drain_plug_washer_info": "Шайбу желательно менять при каждом сливе.",
      "oem_bolt_1": "",
      "oem_bolt_1_price": 0,
      "oem_bolt_1_info": "Болты поддона и момент затяжки зависят от версии.",
      "oem_bolt_2": "",
      "oem_bolt_2_price": 0,
      "oem_bolt_2_info": ""
    },
    "procedure": "Стандартная схема: прогрев, слив ATF, снятие и очистка поддона, замена фильтра и прокладки, сборка, заливка свежей жидкости и контроль уровня по щупу или сервисной процедуре.",
    "mistakes": [
      "Подбор фильтра без проверки VIN.",
      "Контроль уровня без прогрева ATF.",
      "Повторное использование одноразовых уплотнений."
    ],
    "nuances": "У разных исполнений 5R55 отличаются поддоны, пробки и фильтры. Перед заказом расходников нужна сверка по VIN."
  },
  "AKPP_A4LD_E4R44E4R55E5R44E5R55EC3": {
    "gearbox": "A4LD-E, 4R44E, 4R55E, 5R44E, 5R55E (C3)",
    "manufacturer": "Ford",
    "description": "Семейство автоматов на базе C3 для заднеприводных и полноприводных Ford.",
    "weak_points": "Перегрев, износ тормозной ленты, загрязнение гидроблока и ошибки по подбору жидкости.",
    "url": "",
    "cars": [],
    "summary": "A4LD-E / 4R44E / 4R55E / 5R44E / 5R55E | слив 4–5 л | MERCON/MERCON V по версии | контроль уровня по щупу",
    "fluid": "ATF MERCON / MERCON V",
    "drain_volume": 4.5,
    "fluid_type": "ATF",
    "fluid_spec": "Допуск уточнять по VIN и году выпуска",
    "fill_range_celsius": "70-90",
    "work_temp_celsius": "80",
    "dry_capacity": "≈ 10–12 л",
    "service_interval": "Ориентир 50 000–60 000 км",
    "pan_torque_nm": 0,
    "drain_torque_nm": 0,
    "fill_torque_nm": 0,
    "tools": ["подъёмник", "ключи для поддона", "динамометрический ключ", "воронка/шланг", "ёмкость для слива"],
    "parts_list": ["ATF по допуску", "фильтр АКПП", "прокладка поддона", "уплотнение сливной пробки"],
    "oem_json": { "oem_fluid_1": "", "oem_fluid_1_price": 0, "oem_fluid_2": "", "oem_fluid_2_price": 0, "oem_filter_internal": "", "oem_filter_internal_price": 0, "oem_filter_internal_info": "Подбор фильтра по VIN и исполнению поддона.", "oem_filter_external": "", "oem_filter_external_price": 0, "oem_filter_external_info": "", "oem_gasket_1": "", "oem_gasket_1_price": 0, "oem_gasket_1_info": "Прокладка зависит от исполнения.", "oem_gasket_2": "", "oem_gasket_2_price": 0, "oem_gasket_2_info": "", "oem_o_ring_1": "", "oem_o_ring_1_price": 0, "oem_o_ring_1_info": "", "oem_o_ring_2": "", "oem_o_ring_2_price": 0, "oem_o_ring_2_info": "", "oem_drain_plug": "", "oem_drain_plug_price": 0, "oem_drain_plug_info": "Зависит от поддона.", "oem_drain_plug_washer": "", "oem_drain_plug_washer_price": 0, "oem_drain_plug_washer_info": "", "oem_bolt_1": "", "oem_bolt_1_price": 0, "oem_bolt_1_info": "", "oem_bolt_2": "", "oem_bolt_2_price": 0, "oem_bolt_2_info": "" },
    "procedure": "Частичный слив с обслуживанием поддона, заменой фильтра и последующей проверкой уровня по щупу на прогретой коробке.",
    "mistakes": ["Неверный допуск ATF.", "Игнорирование температуры при проверке уровня.", "Перетяжка крепежа поддона."],
    "nuances": "Для семейства C3 детали и допуски нужно проверять по году и VIN."
  },
  "AKPP_AODAOD_E4R70W4R75W4R70E4R75E": {
    "gearbox": "AOD, AOD-E, 4R70W, 4R75W, 4R70E, 4R75E",
    "manufacturer": "Ford",
    "description": "Крупное семейство полноразмерных автоматов Ford для мощных заднеприводных платформ.",
    "weak_points": "Перегрев, износ гидротрансформатора, течи, загрязнение гидроблока.",
    "url": "",
    "cars": [],
    "summary": "AOD / 4R70W / 4R75W | слив 4–6 л | MERCON/MERCON V по версии | уровень по щупу",
    "fluid": "ATF MERCON / MERCON V",
    "drain_volume": 5,
    "fluid_type": "ATF",
    "fluid_spec": "Проверять по году выпуска и табличке коробки",
    "fill_range_celsius": "70-90",
    "work_temp_celsius": "80",
    "dry_capacity": "≈ 12–14 л",
    "service_interval": "Ориентир 50 000–60 000 км; при тяжёлой эксплуатации чаще",
    "pan_torque_nm": 0,
    "drain_torque_nm": 0,
    "fill_torque_nm": 0,
    "tools": ["подъёмник", "набор головок", "динамометрический ключ", "воронка для щупа", "ёмкость для слива 15 л"],
    "parts_list": ["ATF по допуску", "сервисный фильтр", "прокладка поддона", "уплотнения пробок"],
    "oem_json": { "oem_fluid_1": "", "oem_fluid_1_price": 0, "oem_fluid_2": "", "oem_fluid_2_price": 0, "oem_filter_internal": "", "oem_filter_internal_price": 0, "oem_filter_internal_info": "Подбирать по VIN и типу поддона.", "oem_filter_external": "", "oem_filter_external_price": 0, "oem_filter_external_info": "Для тяжёлой эксплуатации часто ставят внешний радиатор, но не штатный фильтр.", "oem_gasket_1": "", "oem_gasket_1_price": 0, "oem_gasket_1_info": "", "oem_gasket_2": "", "oem_gasket_2_price": 0, "oem_gasket_2_info": "", "oem_o_ring_1": "", "oem_o_ring_1_price": 0, "oem_o_ring_1_info": "", "oem_o_ring_2": "", "oem_o_ring_2_price": 0, "oem_o_ring_2_info": "", "oem_drain_plug": "", "oem_drain_plug_price": 0, "oem_drain_plug_info": "", "oem_drain_plug_washer": "", "oem_drain_plug_washer_price": 0, "oem_drain_plug_washer_info": "", "oem_bolt_1": "", "oem_bolt_1_price": 0, "oem_bolt_1_info": "", "oem_bolt_2": "", "oem_bolt_2_price": 0, "oem_bolt_2_info": "" },
    "procedure": "Слить ATF, снять и очистить поддон, заменить фильтр, собрать узел, залить новый объём ATF и проверить уровень по щупу на холостом ходу.",
    "mistakes": ["Смешивание разных допусков ATF.", "Отсутствие охлаждения при тяжёлой эксплуатации.", "Перетяжка поддона."],
    "nuances": "Для 4R70/4R75 и ранних AOD детали поддона и фильтра могут различаться."
  },
  "AKPP_AX4N4F50N": {
    "gearbox": "AX4N, 4F50N",
    "manufacturer": "Ford",
    "description": "Переднеприводные 4-ступенчатые автоматы Ford для Taurus, Windstar и смежных моделей.",
    "weak_points": "Перегрев, проблемы гидроблока и ГДТ, чувствительность к состоянию масла.",
    "url": "",
    "cars": [],
    "summary": "AX4N / 4F50N | слив 4–5 л | обычно MERCON V | контроль уровня по щупу",
    "fluid": "ATF MERCON V",
    "drain_volume": 4.5,
    "fluid_type": "ATF MERCON V",
    "fluid_spec": "Проверять по VIN и мануалу",
    "fill_range_celsius": "70-90",
    "work_temp_celsius": "80",
    "dry_capacity": "≈ 9–11 л",
    "service_interval": "Ориентир 50 000–60 000 км",
    "pan_torque_nm": 0,
    "drain_torque_nm": 0,
    "fill_torque_nm": 0,
    "tools": ["подъёмник", "ключи для поддона", "динамометрический ключ", "воронка для щупа"],
    "parts_list": ["ATF MERCON V", "фильтр АКПП", "прокладка поддона"],
    "oem_json": { "oem_fluid_1": "", "oem_fluid_1_price": 0, "oem_fluid_2": "", "oem_fluid_2_price": 0, "oem_filter_internal": "", "oem_filter_internal_price": 0, "oem_filter_internal_info": "Подбирать по VIN.", "oem_filter_external": "", "oem_filter_external_price": 0, "oem_filter_external_info": "", "oem_gasket_1": "", "oem_gasket_1_price": 0, "oem_gasket_1_info": "", "oem_gasket_2": "", "oem_gasket_2_price": 0, "oem_gasket_2_info": "", "oem_o_ring_1": "", "oem_o_ring_1_price": 0, "oem_o_ring_1_info": "", "oem_o_ring_2": "", "oem_o_ring_2_price": 0, "oem_o_ring_2_info": "", "oem_drain_plug": "", "oem_drain_plug_price": 0, "oem_drain_plug_info": "", "oem_drain_plug_washer": "", "oem_drain_plug_washer_price": 0, "oem_drain_plug_washer_info": "", "oem_bolt_1": "", "oem_bolt_1_price": 0, "oem_bolt_1_info": "", "oem_bolt_2": "", "oem_bolt_2_price": 0, "oem_bolt_2_info": "" },
    "procedure": "Стандартное обслуживание с частичным сливом, снятием поддона, заменой фильтра и выставлением уровня по щупу на горячую.",
    "mistakes": ["Перегрев коробки без чистки радиатора.", "Эксплуатация на старой ATF."],
    "nuances": "На поздних 4F50N и ранних AX4N могут отличаться отдельные расходники."
  },
  "AKPP_AXOD_AXOD_E_AX4S": {
    "gearbox": "AXOD/AXOD-E/AX4S",
    "manufacturer": "Ford",
    "description": "Ранние переднеприводные автоматы Ford семейства AXOD/AX4S.",
    "weak_points": "Высокая чувствительность к загрязнённому маслу и перегреву.",
    "url": "",
    "cars": [],
    "summary": "AXOD / AXOD-E / AX4S | слив 4–5 л | MERCON/MERCON V по версии | уровень по щупу",
    "fluid": "ATF MERCON / MERCON V",
    "drain_volume": 4.5,
    "fluid_type": "ATF",
    "fluid_spec": "Подбирать по году выпуска и мануалу",
    "fill_range_celsius": "70-90",
    "work_temp_celsius": "80",
    "dry_capacity": "≈ 9–10 л",
    "service_interval": "Желательно 40 000–50 000 км",
    "pan_torque_nm": 0,
    "drain_torque_nm": 0,
    "fill_torque_nm": 0,
    "tools": ["подъёмник", "ключи для поддона", "воронка/шланг", "ёмкость для слива"],
    "parts_list": ["ATF по допуску", "фильтр АКПП", "прокладка поддона"],
    "oem_json": { "oem_fluid_1": "", "oem_fluid_1_price": 0, "oem_fluid_2": "", "oem_fluid_2_price": 0, "oem_filter_internal": "", "oem_filter_internal_price": 0, "oem_filter_internal_info": "Зависит от версии AXOD/AX4S.", "oem_filter_external": "", "oem_filter_external_price": 0, "oem_filter_external_info": "", "oem_gasket_1": "", "oem_gasket_1_price": 0, "oem_gasket_1_info": "", "oem_gasket_2": "", "oem_gasket_2_price": 0, "oem_gasket_2_info": "", "oem_o_ring_1": "", "oem_o_ring_1_price": 0, "oem_o_ring_1_info": "", "oem_o_ring_2": "", "oem_o_ring_2_price": 0, "oem_o_ring_2_info": "", "oem_drain_plug": "", "oem_drain_plug_price": 0, "oem_drain_plug_info": "", "oem_drain_plug_washer": "", "oem_drain_plug_washer_price": 0, "oem_drain_plug_washer_info": "", "oem_bolt_1": "", "oem_bolt_1_price": 0, "oem_bolt_1_info": "", "oem_bolt_2": "", "oem_bolt_2_price": 0, "oem_bolt_2_info": "" },
    "procedure": "Обычный сервис со снятием поддона, чисткой магнитов, заменой фильтра и контролем уровня по щупу.",
    "mistakes": ["Редкая замена ATF.", "Езда на перегретой коробке."],
    "nuances": "Для старых коробок часто разумнее делать две последовательные частичные замены."
  },
  "AKPP_CD4ELA4A_EL4F44E": {
    "gearbox": "CD4E, LA4A-EL (4F44E)",
    "manufacturer": "Ford",
    "description": "4-ступенчатая переднеприводная АКПП Ford/Mazda для моторов 2.0–2.5 л.",
    "weak_points": "Тормозная лента, маслонасос, гидроблок и перегрев.",
    "url": "",
    "cars": [],
    "summary": "CD4E / LA4A-EL (4F44E) | слив 4–5 л | обычно MERCON V | контроль уровня по щупу или сервисной процедуре",
    "fluid": "ATF MERCON V",
    "drain_volume": 4.5,
    "fluid_type": "ATF MERCON V",
    "fluid_spec": "Уточнять по VIN и рынку",
    "fill_range_celsius": "70-90",
    "work_temp_celsius": "80",
    "dry_capacity": "≈ 8–9 л",
    "service_interval": "Ориентир 40 000–60 000 км",
    "pan_torque_nm": 0,
    "drain_torque_nm": 0,
    "fill_torque_nm": 0,
    "tools": ["подъёмник", "ключи для поддона", "динамометрический ключ", "воронка/насос"],
    "parts_list": ["ATF MERCON V", "фильтр АКПП", "прокладка поддона", "уплотнения пробок"],
    "oem_json": { "oem_fluid_1": "", "oem_fluid_1_price": 0, "oem_fluid_2": "", "oem_fluid_2_price": 0, "oem_filter_internal": "", "oem_filter_internal_price": 0, "oem_filter_internal_info": "Фильтр и прокладка подбираются по VIN.", "oem_filter_external": "", "oem_filter_external_price": 0, "oem_filter_external_info": "", "oem_gasket_1": "", "oem_gasket_1_price": 0, "oem_gasket_1_info": "", "oem_gasket_2": "", "oem_gasket_2_price": 0, "oem_gasket_2_info": "", "oem_o_ring_1": "", "oem_o_ring_1_price": 0, "oem_o_ring_1_info": "", "oem_o_ring_2": "", "oem_o_ring_2_price": 0, "oem_o_ring_2_info": "", "oem_drain_plug": "", "oem_drain_plug_price": 0, "oem_drain_plug_info": "", "oem_drain_plug_washer": "", "oem_drain_plug_washer_price": 0, "oem_drain_plug_washer_info": "", "oem_bolt_1": "", "oem_bolt_1_price": 0, "oem_bolt_1_info": "", "oem_bolt_2": "", "oem_bolt_2_price": 0, "oem_bolt_2_info": "" },
    "procedure": "Частичный слив, снятие поддона, осмотр ленты и насоса, замена фильтра, сборка и контроль уровня.",
    "mistakes": ["Игнорирование износа ленты.", "Перегрев коробки.", "Подбор расходников без VIN."],
    "nuances": "На части версий применяются кросс-номера Ford/Mazda, поэтому расходники нужно сверять по каталогу."
  },
  "AKPP_E40D4R100C6": {
    "gearbox": "E4OD, 4R100, C6",
    "manufacturer": "Ford",
    "description": "Тяжёлые автоматы Ford для пикапов, внедорожников и коммерческого транспорта.",
    "weak_points": "Перегрев под нагрузкой, загрязнение гидроблока, износ входного вала и насоса.",
    "url": "",
    "cars": [],
    "summary": "E4OD / 4R100 / C6 | слив 5–7 л | MERCON/MERCON V по версии | уровень по щупу | критично состояние охлаждения",
    "fluid": "ATF MERCON / MERCON V",
    "drain_volume": 6,
    "fluid_type": "ATF",
    "fluid_spec": "Уточнять по году и автомобилю",
    "fill_range_celsius": "70-90",
    "work_temp_celsius": "85",
    "dry_capacity": "≈ 14–16 л",
    "service_interval": "Ориентир 40 000–50 000 км; при буксировке и тяжёлой эксплуатации чаще",
    "pan_torque_nm": 0,
    "drain_torque_nm": 0,
    "fill_torque_nm": 0,
    "tools": ["подъёмник", "ёмкость для слива 20 л", "ключи для поддона", "воронка для щупа"],
    "parts_list": ["ATF по допуску", "фильтр АКПП", "прокладка поддона", "уплотнения пробок"],
    "oem_json": { "oem_fluid_1": "", "oem_fluid_1_price": 0, "oem_fluid_2": "", "oem_fluid_2_price": 0, "oem_filter_internal": "", "oem_filter_internal_price": 0, "oem_filter_internal_info": "Подбирать по VIN и версии коробки.", "oem_filter_external": "", "oem_filter_external_price": 0, "oem_filter_external_info": "Штатного внешнего фильтра обычно нет, но охлаждение критично.", "oem_gasket_1": "", "oem_gasket_1_price": 0, "oem_gasket_1_info": "", "oem_gasket_2": "", "oem_gasket_2_price": 0, "oem_gasket_2_info": "", "oem_o_ring_1": "", "oem_o_ring_1_price": 0, "oem_o_ring_1_info": "", "oem_o_ring_2": "", "oem_o_ring_2_price": 0, "oem_o_ring_2_info": "", "oem_drain_plug": "", "oem_drain_plug_price": 0, "oem_drain_plug_info": "", "oem_drain_plug_washer": "", "oem_drain_plug_washer_price": 0, "oem_drain_plug_washer_info": "", "oem_bolt_1": "", "oem_bolt_1_price": 0, "oem_bolt_1_info": "", "oem_bolt_2": "", "oem_bolt_2_price": 0, "oem_bolt_2_info": "" },
    "procedure": "Слить жидкость, обслужить поддон и фильтр, залить свежую ATF, прогреть коробку и перепроверить уровень после тест-драйва под нагрузкой.",
    "mistakes": ["Буксировка без контроля температуры ATF.", "Редкая замена масла.", "Грязный радиатор охлаждения."],
    "nuances": "Для E4OD/4R100 ресурс сильно зависит от температуры и состояния системы охлаждения."
  },
  "AKPP_FW6A_ELGW6A_EL": {
    "gearbox": "FW6A-EL, GW6A-EL",
    "manufacturer": "Mazda",
    "description": "6-ступенчатая автоматическая коробка Mazda/Aisin для переднеприводных Mazda Skyactiv.",
    "weak_points": "Износ ГДТ, загрязнение гидроблока и чувствительность к нарушению уровня.",
    "url": "",
    "cars": [],
    "summary": "FW6A-EL / GW6A-EL | слив ≈ 3,3 л | ATF-FZ | контроль уровня 45–55 °C | ранние и поздние версии отличаются по способу проверки",
    "fluid": "Mazda ATF-FZ",
    "drain_volume": 3.3,
    "fluid_type": "ATF-FZ",
    "fluid_spec": "Mazda ATF-FZ",
    "fill_range_celsius": "45-55",
    "work_temp_celsius": "50",
    "dry_capacity": "7,9 л",
    "service_interval": "60 000 км или 4 года; тяжёлый режим — 30 000 км или 2 года",
    "pan_torque_nm": 0,
    "drain_torque_nm": 35,
    "fill_torque_nm": 9,
    "tools": ["подъёмник", "шестигранник 8 мм", "болт щупа 10 мм", "динамометрический ключ", "OBD-сканер для TFT"],
    "parts_list": ["Mazda ATF-FZ 5 л", "сливная пробка FS50-21-249", "кольцо 9956-41-400", "щуп/болт уровня по версии"],
    "oem_json": {
      "oem_fluid_1": "0000-FZ-113E-01",
      "oem_fluid_1_price": 0,
      "oem_fluid_2": "AJ00-FZ-113E",
      "oem_fluid_2_price": 0,
      "oem_filter_internal": "",
      "oem_filter_internal_price": 0,
      "oem_filter_internal_info": "Фильтр встроен и меняется при разборке гидроблока.",
      "oem_filter_external": "",
      "oem_filter_external_price": 0,
      "oem_filter_external_info": "Отдельного внешнего сервисного фильтра нет.",
      "oem_gasket_1": "",
      "oem_gasket_1_price": 0,
      "oem_gasket_1_info": "",
      "oem_gasket_2": "",
      "oem_gasket_2_price": 0,
      "oem_gasket_2_info": "",
      "oem_o_ring_1": "9956-41-400",
      "oem_o_ring_1_price": 0,
      "oem_o_ring_1_info": "Медная шайба сливной пробки.",
      "oem_o_ring_2": "9956-41-800",
      "oem_o_ring_2_price": 0,
      "oem_o_ring_2_info": "",
      "oem_drain_plug": "FS50-21-249",
      "oem_drain_plug_price": 0,
      "oem_drain_plug_info": "Сливная пробка 8 мм.",
      "oem_drain_plug_washer": "9956-41-400",
      "oem_drain_plug_washer_price": 0,
      "oem_drain_plug_washer_info": "Шайбу желательно менять при каждом сливе.",
      "oem_bolt_1": "",
      "oem_bolt_1_price": 0,
      "oem_bolt_1_info": "Болт щупа уровня зависит от версии.",
      "oem_bolt_2": "",
      "oem_bolt_2_price": 0,
      "oem_bolt_2_info": ""
    },
    "procedure": "Прогреть трансмиссию, слить ATF через сливную пробку, залить объём слитого плюс небольшой запас, затем выставить уровень по щупу или сервисной процедуре при TFT 45–55 °C.",
    "mistakes": ["Проверка уровня вне температурного окна.", "Использование ATF не класса FZ.", "Перетяжка сливной пробки."],
    "nuances": "На ранних версиях используется щуп, на поздних возможна другая методика контроля уровня."
  },
  "AKPP_FW6A_EL": {
    "gearbox": "FW6A-EL, GW6A-EL",
    "manufacturer": "Mazda",
    "description": "Актуализированная карточка Mazda для FW6A-EL / GW6A-EL.",
    "weak_points": "Износ ГДТ и загрязнение гидроблока при редкой замене ATF.",
    "url": "",
    "cars": [],
    "summary": "FW6A-EL / GW6A-EL | слив ≈ 3,3 л | ATF-FZ | контроль уровня 45–55 °C",
    "fluid": "Mazda ATF-FZ",
    "drain_volume": 3.3,
    "fluid_type": "ATF-FZ",
    "fluid_spec": "Mazda ATF-FZ",
    "fill_range_celsius": "45-55",
    "work_temp_celsius": "50",
    "dry_capacity": "7,9 л",
    "service_interval": "60 000 км или 4 года",
    "pan_torque_nm": 0,
    "drain_torque_nm": 35,
    "fill_torque_nm": 9,
    "tools": ["подъёмник", "шестигранник 8 мм", "сканер TFT"],
    "parts_list": ["ATF-FZ", "сливная пробка", "шайба пробки"],
    "oem_json": { "oem_fluid_1": "0000-FZ-113E-01", "oem_fluid_1_price": 0, "oem_fluid_2": "AJ00-FZ-113E", "oem_fluid_2_price": 0, "oem_filter_internal": "", "oem_filter_internal_price": 0, "oem_filter_internal_info": "Фильтр встроен.", "oem_filter_external": "", "oem_filter_external_price": 0, "oem_filter_external_info": "", "oem_gasket_1": "", "oem_gasket_1_price": 0, "oem_gasket_1_info": "", "oem_gasket_2": "", "oem_gasket_2_price": 0, "oem_gasket_2_info": "", "oem_o_ring_1": "9956-41-400", "oem_o_ring_1_price": 0, "oem_o_ring_1_info": "", "oem_o_ring_2": "9956-41-800", "oem_o_ring_2_price": 0, "oem_o_ring_2_info": "", "oem_drain_plug": "FS50-21-249", "oem_drain_plug_price": 0, "oem_drain_plug_info": "", "oem_drain_plug_washer": "9956-41-400", "oem_drain_plug_washer_price": 0, "oem_drain_plug_washer_info": "", "oem_bolt_1": "", "oem_bolt_1_price": 0, "oem_bolt_1_info": "", "oem_bolt_2": "", "oem_bolt_2_price": 0, "oem_bolt_2_info": "" },
    "procedure": "Слить ATF, залить свежую жидкость, прогреть коробку и выставить уровень при 45–55 °C.",
    "mistakes": ["Неверная температура проверки.", "Использование неподходящей жидкости."],
    "nuances": "Разные ревизии используют разные способы контроля уровня."
  },
  "AKPP_6F24": {
    "gearbox": "6F24",
    "manufacturer": "SsangYong",
    "description": "6-ступенчатая АКПП, применявшаяся на ряде моделей SsangYong и смежных платформ.",
    "weak_points": "Износ ГДТ, загрязнение гидроблока, возможные отличия по допуску ATF в зависимости от автомобиля.",
    "url": "",
    "cars": [],
    "summary": "6F24 | слив 4–5 л | ATF по допуску конкретного автомобиля | уровень по щупу или сервисной пробке, зависит от исполнения",
    "fluid": "ATF по допуску производителя автомобиля",
    "drain_volume": 4.5,
    "fluid_type": "ATF",
    "fluid_spec": "Уточнять по конкретному автомобилю и рынку",
    "fill_range_celsius": "уточнять по мануалу",
    "work_temp_celsius": "80",
    "dry_capacity": "≈ 7–9 л",
    "service_interval": "Ориентир 50 000–60 000 км",
    "pan_torque_nm": 0,
    "drain_torque_nm": 0,
    "fill_torque_nm": 0,
    "tools": ["подъёмник", "ключи под поддон", "насос/шприц для ATF", "OBD-сканер"],
    "parts_list": ["ATF по допуску", "фильтр АКПП по версии", "прокладка поддона", "уплотнения пробок"],
    "oem_json": { "oem_fluid_1": "", "oem_fluid_1_price": 0, "oem_fluid_2": "", "oem_fluid_2_price": 0, "oem_filter_internal": "", "oem_filter_internal_price": 0, "oem_filter_internal_info": "Фильтр и его сервисность зависят от конкретной версии 6F24.", "oem_filter_external": "", "oem_filter_external_price": 0, "oem_filter_external_info": "", "oem_gasket_1": "", "oem_gasket_1_price": 0, "oem_gasket_1_info": "Поддон и прокладка зависят от исполнения.", "oem_gasket_2": "", "oem_gasket_2_price": 0, "oem_gasket_2_info": "", "oem_o_ring_1": "", "oem_o_ring_1_price": 0, "oem_o_ring_1_info": "", "oem_o_ring_2": "", "oem_o_ring_2_price": 0, "oem_o_ring_2_info": "", "oem_drain_plug": "", "oem_drain_plug_price": 0, "oem_drain_plug_info": "", "oem_drain_plug_washer": "", "oem_drain_plug_washer_price": 0, "oem_drain_plug_washer_info": "", "oem_bolt_1": "", "oem_bolt_1_price": 0, "oem_bolt_1_info": "", "oem_bolt_2": "", "oem_bolt_2_price": 0, "oem_bolt_2_info": "" },
    "procedure": "Сервис выполняется по схеме конкретного автомобиля: слив, при необходимости снятие поддона и фильтра, заливка свежей жидкости и контроль уровня по штатной процедуре.",
    "mistakes": ["Назначение универсального допуска ATF без проверки мануала.", "Подбор расходников без VIN."],
    "nuances": "Коробка встречается на разных автомобилях, поэтому расходники и процедура могут заметно отличаться."
  }
});
